### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by svickers** [bigmlcom/bigml-csharp#30]
Is this library still being supported? It looks like the BigML package is no longer in nuget.

**Comment by osroca** [comment]
@svickers: this bindings are actively maintained, not as actively as other bindings in other languages (for instance: [bigmlcom/python](https://github.com/bigmlcom/python) or [bigmlcom/bigml-node](https://github.com/bigmlcom/bigml-node)) though. We could accelerate the development if there is really interest. The current state of the bindings is that you can work with BigML REST API with the following resources:
- Sources
- Datasets 
- Models
- Ensembles
- Evaluations
- Clusters
- Anomaly Detectors
- Logistic Regressions
- Correlations
- Predictions / Centroids / Anomaly Score / and all the Batch equivalents 

that is, almost all our resources. In the next days we'll update it with Associations.

The current state of the library also allows you to work with LocalModels (decision trees) that enables you to compute predictions locally without API requests (you need just one GET request to retrieve an existing model from BigML).

As far as we know, the library has never been deployed on nuget. If you need it we can make it public in there.

**Comment by joseribes** [comment]
@svickers, can we close the issue?

**Comment by svickers** [comment]
A nuget package would be pretty convenient, especially for updates, so you don't have to clone and rebuild all the time.  Also makes managing the dependencies like System.Json more straightforward.

**Comment by joseribes** [comment]
The package is available here https://www.nuget.org/packages/BigML/
