### ISSUE TITLE
NuGet Support

### ISSUE THREAD

**Issue by CVertex** [bigmlcom/bigml-csharp#31]
Hey BigML! Of course this library is getting used :+1: 

Please bundle this into a Nuget so it's easy for people to get started using the API using .NET

Thanks

**Comment by joseribes** [comment]
The packages is available here https://www.nuget.org/packages/BigML/

**Comment by CVertex** [comment]
Thanks @joseribes Could you include the package details in the repo itself so we can all see.. It's sometimes important to link/confirm the authenticity of packages
