### ISSUE TITLE
mixed line endings and Update response code handling

### ISSUE THREAD

**Issue by mmerce** [bigmlcom/bigml-csharp#34]
David Marcus reported the app.config file having mixed line endings. He also noticed that the Update call response is never expected to be HTTP_OK but HTTP_ACCEPTED, so the HTTP_OK case could be removed.

**Comment by djmarcus1** [comment]
I also noticed that many source files have Unix line endings.

Examples (folder):
    Centroid
    Cluster
    ...

Its not a big deal but I think they should all have PC (Windows) line endings (CR/LF)
