### ISSUE TITLE
Runtime error in sample project

### ISSUE THREAD

**Issue by cshiel** [bigmlcom/bigml-csharp#5]
I am getting on line 55 of program.cs in Iris project:
An unhandled exception of type 'System.AggregateException' occurred in mscorlib.dll

**Comment by osroca** [comment]
Hi @cshiel, can you verify that the current version of the bindings fixes the issue you are experiencing? If it doesn't, please reopen this issue again.

**Comment by cshiel** [comment]
Its now updated and working thanks.
